---
description: 컴파일러 오류 CS1626
title: 컴파일러 오류 CS1626
ms.date: 07/20/2015
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
ms.openlocfilehash: 234acba50df406bb6ea02cc5b5a8fe0c959027d5
ms.sourcegitcommit: d579fb5e4b46745fd0f1f8874c94c6469ce58604
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 08/30/2020
ms.locfileid: "89142507"
---
# <a name="compiler-error-cs1626"></a>컴파일러 오류 CS1626
catch 절이 포함된 try 블록의 본문에서는 값을 생성할 수 없습니다.  
  
 yield 문은 try 블록과 연결된 catch 절이 있는 경우 try 블록에 사용할 수 없습니다. 이 오류를 방지 하려면 yield 문을 try/catch/finally 블록 밖으로 이동 하거나 catch 블록을 제거 합니다.
  
 다음 샘플에서는 CS1626을 생성합니다.  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
      finally
      {

      }
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
