---
title: "'Throw' 문은 'Catch' 문 외부 또는 'Finally' 문 내부에서 피연산자를 생략할 수 없습니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 05fc14b0f493b3901fda9fbdba7e0fcebae6bea5
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 09/23/2020
ms.locfileid: "91068897"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="edebf-102">'Throw' 문은 'Catch' 문 외부 또는 'Finally' 문 내부에서 피연산자를 생략할 수 없습니다.</span><span class="sxs-lookup"><span data-stu-id="edebf-102">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>

<span data-ttu-id="edebf-103">`Throw` 문 외부의 `Catch` 문에서 예외 개체의 이름을 제공해야 합니다.</span><span class="sxs-lookup"><span data-stu-id="edebf-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="edebf-104">**오류 ID:** BC30666</span><span class="sxs-lookup"><span data-stu-id="edebf-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="edebf-105">이 오류를 해결하려면</span><span class="sxs-lookup"><span data-stu-id="edebf-105">To correct this error</span></span>  
  
1. <span data-ttu-id="edebf-106">`System.Exception`에서 파생된 예외 개체의 이름을 지정합니다.</span><span class="sxs-lookup"><span data-stu-id="edebf-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2. <span data-ttu-id="edebf-107">`Throw` 문이 `Catch` 블록 내부에 있도록 코드를 재구성합니다.</span><span class="sxs-lookup"><span data-stu-id="edebf-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="edebf-108">참조</span><span class="sxs-lookup"><span data-stu-id="edebf-108">See also</span></span>

- [<span data-ttu-id="edebf-109">Throw 문</span><span class="sxs-lookup"><span data-stu-id="edebf-109">Throw Statement</span></span>](../language-reference/statements/throw-statement.md)
- [<span data-ttu-id="edebf-110">Try...Catch...Finally 명령문</span><span class="sxs-lookup"><span data-stu-id="edebf-110">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="edebf-111">.NET의 예외 처리 및 Throw</span><span class="sxs-lookup"><span data-stu-id="edebf-111">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
